# Generated by Django 5.0.1 on 2026-02-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_usercolorpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercolorpreferences',
            name='morning_color',
            field=models.CharField(default='#72CB92', max_length=7),
        ),
        migrations.AlterField(
            model_name='usercolorpreferences',
            name='night_color',
            field=models.CharField(default='#7DA7D7', max_length=7),
        ),
        migrations.AlterField(
            model_name='usercolorpreferences',
            name='noon_color',
            field=models.CharField(default='#D79E63', max_length=7),
        ),
    ]
