# Generated by Django 5.0.1 on 2026-02-01 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColorPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('palette_type', models.CharField(default='default', max_length=20)),
                ('morning_color', models.CharField(default='#22c55e', max_length=7)),
                ('noon_color', models.CharField(default='#f59e0b', max_length=7)),
                ('night_color', models.CharField(default='#3b82f6', max_length=7)),
                ('morning_noon_color', models.CharField(blank=True, max_length=7, null=True)),
                ('morning_night_color', models.CharField(blank=True, max_length=7, null=True)),
                ('noon_night_color', models.CharField(blank=True, max_length=7, null=True)),
                ('all_day_color', models.CharField(blank=True, max_length=7, null=True)),
                ('custom_morning_noon', models.BooleanField(default=False)),
                ('custom_morning_night', models.BooleanField(default=False)),
                ('custom_noon_night', models.BooleanField(default=False)),
                ('custom_all_day', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Color Preferences',
                'verbose_name_plural': 'User Color Preferences',
            },
        ),
    ]
