# Generated by Django 5.0.1 on 2026-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_update_default_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedicine',
            name='dose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
