# Generated by Django 5.0.1 on 2026-03-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_add_timestamp_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalmedicine',
            options={'ordering': ['medicine_name'], 'verbose_name': 'Global Medicine', 'verbose_name_plural': 'Global Medicines'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='usercolorpreferences',
            options={'ordering': ['-updated_at'], 'verbose_name': 'User Color Preferences', 'verbose_name_plural': 'User Color Preferences'},
        ),
        migrations.AlterModelOptions(
            name='usermedicine',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Medicine', 'verbose_name_plural': 'User Medicines'},
        ),
        migrations.AlterField(
            model_name='globalmedicine',
            name='medicine_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usermedicine',
            name='medicine_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name='globalmedicine',
            table='global_medicines',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
        migrations.AlterModelTable(
            name='usercolorpreferences',
            table='user_color_preferences',
        ),
        migrations.AlterModelTable(
            name='usermedicine',
            table='user_medicines',
        ),
    ]
